experiment: "Wystrach2020"
data: "../../data/rawdata/Melophorus_Individual_Data_Paths.csv"
conditions:
  no-trap: partial(operator.eq, 0)
  trap: partial(operator.le, 1)

env_config: "workflow/config/Wystrach2020env.yaml"

actions: INTERCARDINALS

simulation_settings:
  reward: 100
  winds: [0.0]
  trapcost: -100

iterations: 10000

# visualization of trajectories
viz:
  trajectories: True
  heatmaps: True
  stylefile: "config/trajectory.mplstyle"
